# Generated by Django 4.1.7 on 2023-03-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='EmpleadoEdad',
            field=models.SmallIntegerField(),
        ),
    ]
